### PR TITLE
6x speedup for dfs put/get, and several bugfixes 

### PR DESCRIPTION
**Pull request by vicentebolea**
This PR Fixes DICL/EclipseMETA#95

## STATUS
- [x] Its implemented.
- [x] It compiles.
- [x] Its tested.
- [x] Its refactored.

---
Make sure that you squeeze all your commits before merging to master.
You might want to use the following command:

    $ git rebase -i #hash key of base commit     

---

### CODE REVIEW

**Comment by vicentebolea** [comment]
@deukyeon it is changed. The diff takes time to load hehe. BTW got to fix the unit tests.

**Comment by vicentebolea** [comment]
@deukyeon can you review the code. It's a lots of changes but you can just do it briefly. 
After that I will squash all the commits into one and merge :+1:

**Comment by vicentebolea** [comment]
@deukyeon I will merger by 10pm :+1:

**Comment by vicentebolea** [comment]
Hey @deukyeon , you can push the rebased version ;)

**Comment by deukyeon** [comment]
@vicentebolea I ran `git rebase -i` in this local branch, but there are no changed files to push.

**Comment by deukyeon** [comment]
@vicentebolea It seems that I don't understand about rebasing. I'm seeing a document about rebasing now. Sorry.

https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by vicentebolea** [comment]
@deukyeon before merging squash the commit using git rebase -i :). I will do it if there is problem

**Pull request merged**
