### PR TITLE
Logical blocks feature

### PR DESCRIPTION
**Pull request by vicentebolea**
This PR Fixes DICL/EclipseMETA#100
__MERGE_IT_PLEASE__
## BRIEF
This PR adds logical block support to VeloxDFS. The main idea is that VeloxDFS can abstract the physical blocks using logical blocks. Those blocks will be an optimal arrange of replicas which theoretically can improve the performance of the FS. 

## STATUS
- [x] Its implemented.
- [x] It compiles.
- [x] Its tested.
- [x] Its refactored.

---
Make sure that you squeeze all your commits before merging to master.
You might want to use the following command:

    $ git rebase -i #hash key of base commit     

---

### CODE REVIEW

**Comment by vicentebolea** [comment]
@deu

**Comment by vicentebolea** [comment]
@deukyeon can you review this PR :+1:
If you need to check how to configure this new feature, check the sample `.eclipse.json` file in the doc

**Comment by deukyeon** [comment]
@vicentebolea 

This PR depends on "MAPREDUCE".
I am not sure that we have to use the term for logical blocks.

**Comment by vicentebolea** [comment]
Maybe I forgot something but I am not sure what you are meaning that it depends on mapreduce. Where does it depends on mapreduce?

**Comment by deukyeon** [comment]
What I said is the term "mapreduce".
For example, a type of messages is "mapreduce". 
It is used at line 124 in "src/fileleader/file_leader.cc".

**Comment by vicentebolea** [comment]
Oh I see. Yeah I forgot to remove that stuff, we better change the type to "logical_blocks" or something like that. Ill make a commit to correct that

**Pull request merged**
